### ISSUE TITLE
Please close me when reviewed, validated and ready for external release.

### ISSUE THREAD

**Issue by shantenujha** [ATLAS-Titan/misc#1]

**Comment by vivek-bala** [comment]
I followed the instructions in ```https://github.com/ATLAS-Titan/misc/wiki/How-to-set-RP-on-TITAN``` and was able to get the example running on Titan.

Note that I had to compile my gromacs according to the instructions in ```https://github.com/ATLAS-Titan/misc/wiki/Compile-Gromacs-on-TITAN-with-Open-MPI``` (linked from the above wiki). I cannot access the default one in the example since I am not on that project.

**Comment by AA919** [comment]
bin/date has been added to the script. By switching a comment the script start executing /bin/date CUs instead of gromacs CUs. The most tricky things are the building of  gromacs and the setting of the DB. I do not see other difficulties.

**Comment by vivek-bala** [comment]
Assuming this ticket is referring to the RP example on Titan:

I followed the instructions in https://github.com/ATLAS-Titan/misc/wiki/How-to-set-RP-on-TITAN and was able to get the example running on Titan.

Note that I had to compile my gromacs according to the instructions in https://github.com/ATLAS-Titan/misc/wiki/Compile-Gromacs-on-TITAN-with-Open-MPI (linked from the above wiki). I cannot access the default one in the example since I am not on that project.

**Comment by shantenujha** [comment]
Maybe we should provide some guidance on what to use (**always provide a default value!!**)

MongoDB URL (To change)
export RADICAL_PILOT_DBURL=<Mongo db url>

**Comment by AA919** [comment]
Do we have a default value for this cases on the virtual machine?

**Comment by vivek-bala** [comment]
I would suggest creating a db instance on mlab and using the url in the example directly (and avoid asking the user to set it up).

**Comment by AA919** [comment]
mlab offers for free only 500Mb. By experience it gets saturated very 
quickly. If we open one for them then we have to clean the db for them 
every time.

Alessio

**Comment by shantenujha** [comment]
Further suggestions:

1. "**Note that by switching the comment between lines 95 and 96, it is also possible to run /bin/date**"

Please provide explicit instruction.

2. Please provide comments/discussion on what the user should see. How does the user know that N simulations ran.

**Comment by AA919** [comment]
Plus....open a mlab and then share the password on internet is not very safe. At that point we are responsible for that db and what users do with it. I am sure that our collaborators are not malicious, however this is a public repository.

**Comment by shantenujha** [comment]
Do I take it that a default value is not set? If so, please provide default values so it truly runs **"out" of the box.**

"The example consider a single thread gromacs simulation as a CU. The number of CUs and the number of cores can be set by the user"

**Comment by vivek-bala** [comment]
True, but I would say it holds up for quite a while (~4 experiments each with 1K CUs after which I changed the url) for me. You can add a default mlab URL and instructions to setup more URLs via mlab. (I don't think you have the option to clean up an existing db if its a free instance).

I am not sure how the example is being handed over but the mlab credentails can be handed over at the time of the demo.

Or you could use the radical VM but that is also purged regularly (incase session is required post-mortem).

Just helping with some ideas (hopefully doesn't conflict/confuse).

**Comment by AA919** [comment]
I put the address of the virtual machine. Good luck to the administrator

**Comment by AA919** [comment]
Added default case. The script runs 128 CUs on 128 cores if the user does not any input.
Link to the lines of code that determine if  the CUs are gromacs or /bin/date have been put in the wiki
